apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverydashboardcontext
  labels:
    app: deliverydashboardcontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverydashboardcontext
  template:
    metadata:
      labels:
        app: deliverydashboardcontext
    spec:
      containers:
        - name: deliverydashboardcontext
          image: username/deliverydashboardcontext:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
