apiVersion: v1
kind: Service
metadata:
  name: deliverydashboardcontext
  labels:
    app: deliverydashboardcontext
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deliverydashboardcontext
